
language: python
before_script:
  - flake8 .
script:
  - nosetests -v --cover-erase --with-coverage --cover-package=novaagent

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - RELEASE=16.04 TYPE=pypi
  - RELEASE=16.04 TYPE=nosystemd

dist: xenial

install:
  - pip install -e .[tests]
  - sudo apt update -qq
  - if [ $TYPE = pypi ]; then sudo apt install libsystemd-dev; fi
  - if [ $TYPE = pypi ]; then pip install -e .[systemd]; fi
  - if [ $TYPE = dist2 ]; then sudo apt install python-systemd; fi
  - if [ $TYPE = dist3 ]; then sudo apt install python3-systemd; fi

matrix:
  include:
    # 2.6 & 3.4 can only be tested on trusty
    - python: "2.6"
      env:  RELEASE=14.04 TYPE=nosystemd
      dist: trusty
    - python: "3.4"
      env:  RELEASE=14.04 TYPE=nosystemd
      dist: trusty
    # Test with dist python-systemd
    ## trusty with v2.7
    - python: "2.7"
      env:  RELEASE=14.04 TYPE=dist2
      dist: trusty
    ## xenial with v2.7 & v3.5
    - python: "2.7"
      env: RELEASE=16.04 TYPE=dist2
      dist: xenial
    - python: "3.5"
      env: RELEASE=16.04 TYPE=dist3
      dist: xenial
