name: Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.6', '3.7', '3.8' ]
        operating_system: [ 'ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-latest']
    name: Unit Tests ${{ matrix.operating_system }}
    runs-on: ${{ matrix.operating_system }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}